version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  nodejs-server:
    build:
      context: ./nodecicd
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: docker-node-cont
    volumes:
       - ./nodecicd:/usr/src/docker compose/nodecicd
       - /usr/src/docker compose/nodecicd/node_modules
  vue-ui:
    build:
      context: ./testcicd
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: docker-vue-cont
    volumes:
       - ./testcicd:/usr/src/docker compose/testcicd
       - /usr/src/docker compose/testcicd/node_modules
       
volumes:
  db:
    driver: local
  